language: node_js
node_js:
    - "Fermium"

install:
    - npm install codecov -g
    - npm install -g yarn
    - yarn

jobs:
    include:
        - script: yarn test --coverage

addons:
    code_climate:
        repo_token: 409795f5026e32a2d7c9b52b97244d14b2c577e2842265fccf6edaa29fe41ff6

sudo: false

after_success:
  - codecov